### PR TITLE
C2PA Theme / Redesign

### PR DESCRIPTION
**Pull request by dkozma**
This adds a custom Hugo C2PA theme based on [TailwindCSS](https://tailwindcss.com/). It is mobile friendly and should close out #12 and #13.

**Note:** This also removes the restrictive `robots.txt` that was in there originally since I assumed you want this to be indexed by search engines - please let me know if not and I can restore it.

Also, this seems like the `/docs` directory is fully generated from the build process - I'm guessing this is the directory that is exposed to Github pages (I don't have access to the repo settings to confirm). If so, I wonder if we may want to use Github Actions to run the build step and deploy to Github pages, since this PR is quite massive with the updates in that directory.

### CODE REVIEW

**Comment by dkozma** [comment]
@lrosenthol Also quick question - I used a [Hugo Tailwind Starter](https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter) project to streamline setting up Tailwind with Hugo. It seems like the MIT-based `LICENSE` file was copied over into the new theme (themes/hugo-theme-c2pa/LICENSE). I'm not sure what the rules are around that - I essentially used the output of the starter as far as Hugo configuration goes, however pretty much all of the presentation is custom. Just wanted to make you aware in case this requires any updates.

**Comment by lrosenthol** [comment]
@dkozma Yes, at some point it would be nice to have an Action to auto-build...in the meantime, yes, you need to do it yourself and upload.

And MIT license is fine, thanks!

**Review by lrosenthol — APPROVED** [review]
LGTM - thanks!

**Review by jorydotcom — CHANGES_REQUESTED** [review]
This is about a billion times better looking than the current site! Thank you @dkozma!! I did find a couple of fixes I think we should make before go live, though, and one question - building locally I had to do an `npm-install` to fetch the postcss-purgecss package; I assume we've accounted for that in our build step? Else it will error. 

* FAQ appears twice in the menu; spacing a bit funny between page title and nav
Screen Shot 2021-04-23 at 3 36 44 PM

* There's a weird thing that happens with this little sizing bug on the small screen, it covers the nav at certain points. Is it meant to be hidden? 
Screen Shot 2021-04-23 at 3 31 41 PM
Screen Shot 2021-04-23 at 3 44 21 PM

**Comment by jorydotcom** [comment]
and it looks like you rm'd the size indicators while I was commenting - sorry! thanks @dkozma

**Comment by dkozma** [comment]
Thanks @jorydotcom - Are you using the docker image to build? I updated the image so that it should have all the postcss dependencies there, so hopefully you won't need that installed on your system going forward.

>FAQ appears twice in the menu; spacing a bit funny between page title and nav

I'm not seeing that, and the menu on the screenshot you took does look funny - perhaps the CSS didn't build correctly for whatever reason? I'm building the compiled site code using the docker image and I'm getting the following result: 
https://user-images.githubusercontent.com/5513876/115943222-a79e4700-a47c-11eb-8b75-287dae0b1602.mov

>There's a weird thing that happens with this little sizing bug on the small screen, it covers the nav at certain points. Is it meant to be hidden?

Yes, I did remove that - good catch.

**Comment by dkozma** [comment]
@jorydotcom - sorry, this was my fault - I didn't realize that the theme files weren't getting built in the docker container. I just pushed up a fix which should make `./hugo-build.sh` publish to the `/docs` directory correctly.

**Comment by dkozma** [comment]
OK - fixed that double FAQ issue as well. I lowercased the `FAQ` folder to `faq` for consistency, and I guess git doesn't pick that up by default, so I had to run some `git mv` commands to ensure it picked up the change.

**Comment by dkozma** [comment]
Validated these issues are resolved with @andyparsons - merging now.

**Pull request merged**
