### PR TITLE
Update FAQ to be more privacy-neutral

### PR DESCRIPTION
**Pull request by andrewjenks**
As discussed in email.

### CODE REVIEW

**Comment by hugovincent** [comment]
LGTM

**Comment by andrewjenks** [comment]
Added two proposed language updates from Sam to make stance on privacy more apparent.

**Review by Spbalogh — COMMENTED** [review]
LGTM

**Comment by sherif-truepic** [comment]
LGTM

**Review by lrosenthol — APPROVED** [review]

**Pull request merged**
