### PR TITLE
Public docs used during recruitment

### PR DESCRIPTION
**Pull request by jpradocueva**
This PR creates a new folder and uploads three documents related to recruitment.
We need public storage for these documents that can be referred by emails and the public C2PA website.

### CODE REVIEW

**Comment by jorydotcom** [comment]
@jpradocueva Did you also want to link to these on the site somewhere?

**Comment by jpradocueva** [comment]
@jorydotcom, yes, I think that the C2PA Introduction deck should also be linked from the website, but I was waiting for the new new revamped pages to see where it should be. With regards to the Questionnaire document, I don't think that it is needed to link it to the website. The decision to send the Questionnaire is done by the Steering Committee.

**Comment by jpradocueva** [comment]
@lrosenthol @jorydotcom are we ok to approve this PR?
We should also link one of the documents "C2PA Introduction Deck" to the website. Any suggestions where the link should be added?

**Comment by lrosenthol** [comment]
Are you sure we want to link the Intro deck on the website?  Do we have a well prepared PDF version that we could use?

**Comment by jpradocueva** [comment]
@lrosenthol the reason for uploading the PDF in the repository is because, we are planning to include this "C2PA Introduction Deck" in the emails automated by the HubSpot workflow. We need a public place where the users can download the document even if they don't have a GitHub account. 

The presentation has been already added to the website via this PR. The documents were added to the `/static/files` folder.


See a reference to the PDF version, there is also a pptx presentation and the questionnaire Word document included in this PR.
https://github.com/c2pa-org/c2pa-org.github.io/pull/24/files#diff-9a14fabda92fcaee3a31638fbd433219c7a6cdd0ba913a6f998db82fad00ae6b

**Comment by jpradocueva** [comment]
@lrosenthol I do expect that this version will have to be updated regularly as the document contains the company logos. But if we keep the same file name, we don't need to update the links in the automated emails.

**Pull request closed without merging**
